ABSOLUTE_PATH=/opt/gitlab
TZ=Europe/Berlin
SERVICES_TRAEFIK_LABELS_TRAEFIK_HOST=HOST(`${GITLAB_FQDN}`)
HETZNER_API_TOKEN=${HETZNER_API_TOKEN}
HETZNER_API_KEY=${HETZNER_API_TOKEN}
ACME_EMAIL=${ACME_EMAIL}
